tools:

    # https://scrutinizer-ci.com/docs/tools/php/security-advisory-checker/
    sensiolabs_security_checker: true

    # https://scrutinizer-ci.com/docs/tools/php/code-sniffer/
    php_code_sniffer:
        enabled: true
        command: phpcs
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    #
    php_cpd:
        enabled: true
        command: phpcpd
        excluded_dirs:
            - 'bin/*'
            - 'vendor/*'
            - 'features/*'

    # https://scrutinizer-ci.com/docs/tools/php/cs-fixer/
    php_cs_fixer:
        enabled: true
        command: php-cs-fixer
        config:
            level: psr2
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    # https://scrutinizer-ci.com/docs/tools/php/mess-detector/
    php_mess_detector:
        enabled: true
        command: phpmd
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'

    # https://scrutinizer-ci.com/docs/tools/php/pdepend/
    php_pdepend:
        enabled: true
        command: pdepend
        excluded_dirs:
            - bin
            - vendor
            - features

    # https://scrutinizer-ci.com/docs/tools/php/php-analyzer/
    php_analyzer:
        enabled: false
        filter:
            excluded_paths:
                - 'bin/*'
                - 'vendor/*'
                - 'features/*'
